services:
  s3:
    container_name: s3
    image: localstack/localstack:s3-latest
    ports:
      - "127.0.0.1:${S3_PORT}:4566"
    environment:
      - DEBUG=0
    volumes:
      - s3:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  s3:
