version: "3.8"

services:
  s3:
    container_name: s3
    image: localstack/localstack:s3-latest
    ports:
      - ${S3_ENDPOINT}:4566
    environment:
      - DEBUG=0
    volumes:
      - s3:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  s3:
