export const AUTH_RULES = {
  MAX_EMAIL_LENGTH: 254,
  MIN_PASSWORD_LENGTH: 7,
  ONE_DIGIT_LETTER_REGEX: /\d/,
  ONE_LOWERCASE_LETTER_REGEX: /[a-z]/,
  ONE_UPPERCASE_LETTER_REGEX: /[A-Z]/,
  ONE_SPECIAL_CHARACTER_REGEX: /[*.!@#$%^&(){}[\]:;<>,.?/~_+-=|]/,
};
