export const CREATE_ROLE_PERMISSION = "Create role";

export const UPDATE_ROLE_PERMISSION = "Update role";

export const VIEW_ALL_WORKFLOWS_PERMISSION = "View all workflows";

export const ALL_PERMISSIONS = [
  CREATE_ROLE_PERMISSION,
  UPDATE_ROLE_PERMISSION,
  VIEW_ALL_WORKFLOWS_PERMISSION,
];
